config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'profile/show'
  
  devise_for :users, controllers: {registrations: 'registrations'}
 
  resources :addresses

  resources :categories
  # get    '/login',   to: 'sessions#new'
  # post   '/login',   to: 'sessions#create'
  # delete '/logout',  to: 'sessions#destroy'

  resource :users do
    resource :carts 
  end

  root "products#index"

  resources :products

  resources :cart_items
  get "/decrement", to: "cart_items#decrement"
  get "/increment", to: "cart_items#increment"
  get "/all_items", to: "carts#all_items"

  resources :order_items
  get "/increment_items", to: "order_items#increment_items"
  get "/decrement_items", to: "order_items#decrement_items"

  resource :users do 
    resources :orders
  end

   

end

app/models/address.rb
class Address < ApplicationRecord
  has_rich_text :content
  belongs_to :user
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart 
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many :order_items
  has_many :cart_items
  belongs_to :categories, optional: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :addcart       
  has_many :orders
  has_one :cart
  has_many :addresses   
  
  after_create :send_welcome_email

  private
  def send_welcome_email
    SendEmailsJob.perform_now(self)
  end

  
  def addcart
    # self.create_cart!
    @cart = Cart.create(user_id: id)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :authenticate_user!, except: [:show]

  def all_items
    if (current_user && @current_cart) || current_user
      @cart_items = current_user.cart.cart_items 
    else
      @cart_items = @current_cart.cart_items
    end
  end

  def show
    if current_user && @current_cart 
      @cart_items = current_user.cart.cart_items
    elsif current_user
      @cart_items = current_user.cart.cart_items
    else
      @cart_items = @current_cart.cart_items
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @order = current_user.orders 
    @orderitems = OrderItem.all
    @cart_items = current_user.cart.cart_items
    
  end

  def show
    @order = current_user.orders    
    @todaysorder = @order.find_by(date: Date.current)
    @orderitems = @todaysorder.order_items
    
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/all_items.html.erb
<h4><b>Continue to place order</b></h4>

Your Address:
<% current_user.addresses.each do |address| %>
  <% if address.primary %>
    Primary Address: 
  
      <% if address.office %>
         Office:
      <% else %>
         Home: 
      <% end %>  

      <%= address.address_line1%>
      <%= address.address_line2%>
      <%= address.city%>
      <%= address.state%>
      <%= address.country%>
      <%= address.pincode%>
    <br>
 <% end %>
<% end %><hr>

<% @cart_items.each do |cartitem| %>
  <div class="card mb-3" style="width: 50rem;">
    <div style= "padding: 3%; padding-top: 3%; padding-bottom: 0%">
      <div class="row">
        <div class= "col"><%= image_tag cartitem.product.image , style: "width: 50%; height: 60%;"%></div>
          <div class= "col">
            <h4><%= cartitem.product.name%></h4>
            <%= cartitem.product.description%> 
            <br>Price: <div class="bi bi-currency-rupee"><%= cartitem.total_price%></div>
          </div>
      </div>
    </div>
  </div>
<% end %>

<div>
  <h4> Balance: <%= @cart_items.sum(:total_price) %></h4> 
  <h3><%= button_to "Continue", style:"background-color: yellow"%></h3>
</div>

app/views/carts/show.html.erb
<h3>My Cart</h3>

<% if @cart_items.exists?%>
  <div>
    <% @cart_items.each do |cartitem| %>
      <div class="card" style="width: 50rem;">
        <div style= "padding: 3%; padding-top: 3%; padding-bottom: 0%">
          <div class="row">
            <div class= "col"><%= image_tag cartitem.product.image , style: "width: 50%; height: 80%;"%></div>
              <div class= "col">
                <h5><%= cartitem.product.name%></h5><hr>
                <%= cartitem.product.description%><br>
                Price: <div class="bi bi-currency-rupee", style="font-size: 20px;"><%=cartitem.total_price%></div> 
                  Added Quantity:
                  <b><%= link_to "+", increment_path(product_id: cartitem.product_id) %></b>
                     <%= cartitem.quantity%> 
                  <b><%= link_to "-", decrement_path(product_id: cartitem.product_id) %></b>
              </div>
          </div> 
        
   
            <p class="row">  
              <%= button_to "Remove Product", cart_item_path(cartitem.product), :method => :delete, data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                          } ,class:"btn btn-danger", style: "border-radius: 20px"%>
            </p>
        </div>
      </div><br> 
    <% end %>
  </div>

<p><%= button_to "Add More Items", products_path(product: @product) , :method => :get ,class:"btn btn-warning"%></p>
 

<div class="row">
  <div class="col", style="padding-top: 1%;"> Amount: <%= @cart_items.sum(:total_price) %></div> 
    <div class="col"><%= button_to "Buy Now", all_items_path(@cart_items), :method => :get,  class:"btn btn-success"%></div>  
      <div>Total Products: <%= @cart_items.sum(:quantity)%></div>
</div>

<% else %>
  <h1 class="bi bi-emoji-frown-fill"></h1>
  <b style="justify-content: center;">Your Cart is Empty</b>
<% end %>

app/views/orders/index.html.erb
<h3>Your Orders</h3>
<div>
  <div class="card", style="width: 100%; padding: 2%;">
    <% @orderitems.each do |orderitems| %>
      Ordered On: <%= orderitems.order.date.strftime("%d/%m/%Y")%>
        <div class="card", style="width: 100%;height:20%">
          <div class="row">
            <div class="col">
              <%= image_tag orderitems.product.image, style: "width: 40%"%><br>
            </div> 
            <div class="col">
              <div class="card-body"> 
                <%=link_to orderitems.product.name, orderitems.product%><br>
                <%=orderitems.product.description%><br> 
                Ordered Quantities:<%=orderitems.quantity%><br>
                Total: <p class="bi bi-currency-rupee"><%= orderitems.total_price %><p>
              </div>
            </div>
          </div>
        </div>  
      <% end %>        
    </div>
</div>

app/views/orders/show.html.erb
<br>
<% current_user.addresses.each do |address| %>
  <% if address.primary %>
    Your Primary Address: 
    <br>
      <% if address.office %>
         Office:
      <% else %>
         Home: 
      <% end %>  

      <%= address.address_line1 %>
      <%= address.address_line2%><br>
      <%= address.city%>
      <%= address.state%>
      <%= address.country%><br>
      <%= address.pincode%>
    <br>
 <% end %>
<% end %><hr>

<div  class="card" style="width: 100%;">
  <% @orderitems.each do |order| %>
    <div class="row">
      <div class="col">
        <div><%= image_tag order.product.image , style: "width: 40%"%></div><br>
      </div> 
        <div class="col">
          <div class="card-body"> 
            <h5 class="card-title"><%= order.product.name%></h5>
            <%= order.product.description%><br>
            Total Quantity: 
            <b><%= link_to "+", increment_items_path(product_id: order.product.id) ,:method => :get %></b><%= order.quantity%>
            <b><%= link_to "-", decrement_items_path(product_id: order.product.id) ,:method => :get%></b><br>
            Total Price: <%= order.total_price%> 

            <p>  
              <%= button_to "Remove item", order_item_path(order.product), :method => :delete, data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                          } , class: "btn btn-danger" %>
            </p>
          </div>
        </div>
    </div>
  <% end %>
</div>
<br>
<h4>Balance: <%= @orderitems.sum(:total_price) %></h4>
 
<%= button_to "Place Order" , class: "btn btn-warning" %>