config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'profile/show'
  
  devise_for :users, controllers: {registrations: 'registrations'}
 
  resources :addresses

  resources :categories
  # get    '/login',   to: 'sessions#new'
  # post   '/login',   to: 'sessions#create'
  # delete '/logout',  to: 'sessions#destroy'

  resource :users do
    resource :carts 
  end

  root "products#index"

  resources :products

  resources :cart_items
  get "/decrement", to: "cart_items#decrement"
  get "/increment", to: "cart_items#increment"
  get "/all_items", to: "carts#all_items"

  resources :order_items
  get "/increment_items", to: "order_items#increment_items"
  get "/decrement_items", to: "order_items#decrement_items"

  resource :users do 
    resources :orders
  end

   

end

app/models/address.rb
class Address < ApplicationRecord
  has_rich_text :content
  belongs_to :user
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart 
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many :order_items
  has_many :cart_items
  belongs_to :categories, optional: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :addcart       
  has_many :orders
  has_one :cart
  has_many :addresses   
  
  after_create :send_welcome_email

  private
  def send_welcome_email
    SendEmailsJob.perform_now(self)
  end

  
  def addcart
    # self.create_cart!
    @cart = Cart.create(user_id: id)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :authenticate_user!, except: [:show]

  def all_items
    if (current_user && @current_cart) || current_user
      @cart_items = current_user.cart.cart_items 
    else
      @cart_items = @current_cart.cart_items
    end
  end

  def show
    if current_user && @current_cart 
      @cart_items = current_user.cart.cart_items
    elsif current_user
      @cart_items = current_user.cart.cart_items
    else
      @cart_items = @current_cart.cart_items
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :mycart

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    
    if @product.save     
      redirect_to @product
    else
      render :new
    end

  end

  def edit
    @product = Product.find(params[:id])
  end
  
  def update
 
    @product = Product.find(params[:id])
 
    if @product.update(product_params)     
      redirect_to @product
    else
      render :edit
    end

  end

  def destroy
    @product = Product.find(params[:id])
     
    @product.destroy
    redirect_to products_path, status: :see_other
  end

  def mycart
    if (current_user && @current_cart) || @current_user
      @cart_items = current_user.cart.cart_items
    else
      @cart_items = @current_cart.cart_items
    end
  end

  private 
  def product_params 
    params.require(:product).permit(:name, :description, :category, :price, :quantity, :image)
  end
  
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<div class="card" , style="padding: 2%">
<%= form_with model: product do |form| %>
  
  <div>
  
    <%= form.label :name %><br>
    <%= form.text_field :name , class: "form-control"%>

    <% product.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>

  </div>
  
  <div>

    <%= form.label :description %><br>
    <%= form.text_area :description ,class: "form-control"%>

    <% product.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>

  </div>

  <div>

    <%= form.label :price %><br>
    <%= form.number_field :price ,class: "form-control"%> 

    <% product.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>    
  
  </div>

  <div>

    <%= form.label :quantity %><br>
    <%= form.number_field :quantity ,class: "form-control"%> 

    <% product.errors.full_messages_for(:quantity).each do |message| %>
      <div><%= message %></div>
    <% end %>    
  
  </div>

  <div>
    <%= form.label :image %><br>
    <%= form.file_field :image ,class: "form-control"%>
  </div> 

  <br>

  <div>
    <%= form.label :category %><br>
    <%= form.select :category, ["Electronics", "Fashion", "Books", "Home"] %>
  </div>

  <div>
    <%= form.submit%>
  </div>
  
<% end %>
</div>

app/views/products/edit.html.erb
<h2> Edit Product </h2>
<%= render "form" , product: @product%>

app/views/products/index.html.erb
<div class="container text-center">
  <div class="row">

    <% @products.each do |product|%>
      <div class="col-3">
        <div class="card shadow-lg bg-body-tertiary rounded">
          <%= link_to product do %>
            <%= image_tag product.image, class: "card-image-top", style: "width: 100%; height: 170px" %>
          <% end %>

          <div class="card-body" style="text-align: left;">
            <h5 style="color: dark-blue"><%= product.name%></h5>
            <div class="container text-center">
              <div class="row" >               
                <div class="col", style="padding: 0px;"><%= button_to "Add to cart", cart_items_path(product: product.id), class: "btn btn-warning"%></div>
                <div class="col", style="padding: 0px;"><%= button_to "Buy Now", order_items_path(product: product.id), class: "btn btn-warning"%></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>
<br>

<%= link_to "Add Product", new_product_path(@product), class: "btn btn-primary" %>

app/views/products/new.html.erb
<h2> Add Product </h2>
<%= render "form" , product: @product%>

app/views/products/show.html.erb
<div class="container text-center">
  <div class="row row-cols-2">
    <div><%= image_tag @product.image , style: "width: 65%; height: 90%" %></div>
    
      <div>
        <h3 class="col"><%= @product.name %></h3>
          <div class="col"><%= @product.description %><br>
            <b class="bi bi-currency-rupee">Price: <%= @product.price %></b><hr>
            <%= button_to "add to cart", cart_items_path(product: @product), class: "btn btn-warning", style:"padding-left: 40%; padding-right: 40%; border-radius: 30px"%><br>
            <%= button_to "Buy Now", order_items_path(product: @product) , class: "btn btn-warning", style:"padding-left: 41%; padding-right: 41%; border-radius: 30px;"%>
          </div>
      </div>
      
  </div>  
</div> 


<br><%= link_to "Edit", edit_product_path(@product) %>

<p><%= button_to "Destroy Product", product_path(@product),:method => :delete, data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
            } %></p>